pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        skipStagesAfterUnstable()
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Clean & Build') {
            steps {

                sh "./mvnw clean install -DskipTests"
            }
        }

        stage('Test') {
            steps {
                sh "./mvnw test"
            }
        }

        stage('Deployment') {
            steps {
                sh 'nohup ./mvnw spring-boot:run -Dserver.port=8001 &'
            }
        }
    }
}